bl_user:
    resource: "@BLUserBundle/Controller/"
    type:     annotation
    prefix:   /

bl_platform:
    resource: "@BLPlatformBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path: /login
    defaults:
        _controller: BLUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout