services:
  bl_platform.antispam:
    class: BL\PlatformBundle\Antispam\BLAntispam
    arguments:
      - "@mailer"
      - %locale%
      - 50
  bl_platform.email.application_mailer:
      class: BL\PlatformBundle\Email\ApplicationMailer
      arguments:
          - "@mailer"
  bl_platform.doctrine_listener.application_creation:
    class: BL\PlatformBundle\DoctrineListener\ApplicationCreationListener
    arguments:
      - "@bl_platform.email.application_mailer"
    tags:
      - { name: doctrine.event_listener, event: postPersist }
  bl_platform.validator.antiflood:
    class: BL\PlatformBundle\Validator\AntifloodValidator
    arguments: ["@request_stack", "@doctrine.orm.entity_manager"]
    tags:
      - { name: validator.constraint_validator, alias: bl_platform_antiflood }
