<?php

namespace BL\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAdverts($page, $nbPerPage) {
        $query = $this->createQueryBuilder('a')
            ->leftJoin('a.image', 'img')
            ->addSelect('img')
            ->leftJoin('a.categories', 'cat')
            ->addSelect('cat')
            ->orderBy('a.date', 'DESC');
        $query
            ->setFirstResult(($page-1) * $nbPerPage)
            ->setMaxResults($nbPerPage);

        return new Paginator($query);
    }

    public function getAdvertWithCategories(array $categoryNames) {
        $qb = $this
            ->createQueryBuilder('a')
            ->innerJoin('a.categories', 'cat')
            ->addSelect('cat');

        $qb->where($qb->expr()->in(
            'cat.name', $categoryNames
        ));

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function getAdvertWithContracts(array $contractTypes) {
        $qb = $this
            ->createQueryBuilder('a')
            ->innerJoin('a.contracts', 'co')
            ->addSelect('co');

        $qb->where($qb->expr()->in(
            'co.type', $contractTypes
        ));

        return $qb
            ->getQuery()
            ->getResult();
    }
}
