<?php

namespace BL\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getApplicationsWithAdvert($limit) {
        $qb = $this
            ->createQueryBuilder('app')
            ->innerJoin('app.advert', 'ad')
            ->addSelect('ad');

        $qb->setMaxResults($limit);

        return $qb
            ->getQuery()
            ->getResult();
    }
}
